### ISSUE TITLE
Make mobile "Filter by tags" chevron icon clickable

### ISSUE THREAD

**Issue by arabello** [espanso/hub-frontend#14]
![image](https://user-images.githubusercontent.com/16003164/169218792-ad491ee1-a6ab-4c37-979c-f44f0ab13191.jpeg)

On explore section mobile, only the text "Filters by tags" is clickable. It would be more intuitive for the user to have the associated chevron icon clickable as well.

**Comment by senali-d** [comment]
Hi,
Shall I work on this issue?

**Comment by arabello** [comment]
Hi! That would be great, feel free to give it a try! Thank you
