### ISSUE TITLE
Handle package decode failure at build time to avoid deploying an empty hub

### ISSUE THREAD

**Issue by federico-terzi** [espanso/hub-frontend#28]
While tags are present in most packages,  probably they shouldn't be mandatory. Could we make it so that the website is still functional if a package without tags is merged? :)

Learned this the hard way after merging this package and the Hub went down :D https://github.com/espanso/hub/pull/35

**Comment by arabello** [comment]
There is no doubt that the lack of tags should not cause a crash in the hub app. The technical bug will be addressed.

Nonetheless, on a UX perspective, I'm not 100% sure we should allow packages with no tags. To me, tags help the user to explore the hub other than keeping the packages well organized. Packages with no tags may be less prone to be discovered by the user.

What do you think? Is there a way for the hub data to enforce having at least a tag? I would even discuss the possibility to have featured-kind-of tags as a way to improve packages organization and visibility.

**Comment by federico-terzi** [comment]
@arabello Good point, I guess the best strategy would be to update the package starter template, as that contains no tags, and the docs (maybe with a list of tags). What do you think?

**Comment by arabello** [comment]
Yes, given that typing enforcing is done via manual approval of a package (correct me if I'm wrong), the only way to ensure the presence of a property is to include it in the documentation _and_ in the template.

NB: I see no point in having an _empty_ `tags` property, so the docs should specify to add at least one tag. For a user point of view, other properties make no sense without a valid value (eg. empty string for the name makes no sense to them). Instead having an _empty_ `tags` list could be seen by the user as a valid approach (eg. my package has no specific categorization, I'll leave it empty). IMHO, such case should be avoided by rejecting the package.

**Comment by arabello** [comment]
This issue should be generalize to whatever package decode failure (eg. missing property). Because we are using static generation, the failure should be handled at build time. In this way, an inconsistent hub will not be deployed at all.
