### ISSUE TITLE
Avoid including erroneous packages in the bundle at built time

### ISSUE THREAD

**Issue by arabello** [espanso/hub-frontend#44]
See #43 for details

**Comment by arabello** [comment]
![IMG_8680](https://github.com/user-attachments/assets/fb9738f5-f8ca-493c-bf27-e81808374cdf)

**Comment by arabello** [comment]
![IMG_8682](https://github.com/user-attachments/assets/081062ea-e498-4f72-9543-1e3e6b83eb25)

**Comment by arabello** [comment]
# AS-IS
Key insights on how the build process happens with regards to espanso hub.
- Build starts from a page: `search` doest not require the package content (repo) as oppose to the detailed page `[version]`. `[packageName]` is just a proxy to make package page URL friendly and renders the latest version.
- The page fetches the packages index which is the structured information provided by the espanso hub. This is the API between the hub and the web app. The [package specification](https://espanso.org/docs/packages/package-specification/) indirectly dictated which object fields are optional or mandatory in the packages index.
- The packages index fetch uses a cache to avoid downloading the index for each page
- Each package details page (`[version]`) fetches the package repository (zip file) to extract the README and package code files, then renders the content. In this page we have the most source of failures. ATM the most relevant issues are:
    -   README serialization failure: if the syntax used for the GitHub readme differs from the one supported by the third party library rendering the readme content, it may raise an error which results in a `BLANK PAGE`
    - missing `homepage` field: the GitHub readme may refers to assets in the package repository. Typically, but not always, the `homepage` field is filled with the GitHub repository link, so we use it to correctly resolve the assets statically served by the GitHub. If, something goes wrong OR the `homepage` field is missing OR the `homepage` field is not a GitHub link then it results in a `MISSING DESC TAB` issue.

# TO-BE
The primary goal is to refactor how the web app is built so we can avoid to include failed package in the build. I think it is preferable to avoid including erroneous ones so they can be easily detected and they don't affect UX. In this way we can also tackle possible issues we are aware of as a lot of things may fail other the ones described. Afterwards, we can specifically improve the `BLANK PAGE` and `MISSING DESC TAB` issues to reduce the possibility of failures.

My current idea is to:
- Extract the checks logic from the fetch package repo in a separeted routine (parse) so we can better select when to include a package or not in a build
- Make the entire logic a unified pipeline over the entire application instead of per page build so we can anticipate which pages should be actually built. For example, we could avoid fetching a package repo is something is wrong at packages index level.

This is an overview, details must be further investigated, but I need to make some code changes before detailing more.

**Comment by arabello** [comment]
PS: because `fp-ts` and generally FP is friction for people wanting to help out, I am thinking to use imperative paradigm in this part rewrite. Also, I myself am not using `fp-ts` daily anymore

**Comment by AucaCoyan** [comment]
Thank you for the diagrams! 💯 
Reviewing the pr 💛
